### ISSUE TITLE
Migrate to Github Pages and Regenerate historical docs

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/rustworkx#1035]
Per https://github.com/Qiskit/ecosystem/issues/611, we accidentally deleted all ecosystem subsites when sunsetting qiskit.org.

Rustworkx is live, but the historical API docs are not yet for 0.8 - 0.13. 

If any of these fail to build, we should modify this to start later and redeploy the docs for the current version, so that the bad release doesn't show up in the left sidebar:

https://github.com/Qiskit/rustworkx/blob/4838d399e4be4623314a3dffcbb0ddd6b8021d20/docs/source/conf.py#L136

**Comment by IvanIsCoding** [comment]
> Hey @IvanIsCoding, how did you deploy to https://qiskit.github.io/rustworkx/ with both the un-versioned docs and also 0.13 docs at https://qiskit.github.io/rustworkx/stable/0.13? I don't see the GH Pages code for it.
> 
> Specifically, I'm wondering if you had to upload the two subsites in one distinct run? Or you could do them separately, like first deploy unversioned, then later add `/stable/0.13`? I imagine adding `/stable/0.13` on its own would overwrite the existing site.

I manually created the folder under the `gh-pages` branch. Essentially, the workflow to deploy the latest version needs to always keep the `stable/` folder. And the workflow to deploy a stable version shouldn't touch the latest code and should just create a new folder

**Comment by IvanIsCoding** [comment]
Concluded with #1037 and #1052
