### ISSUE TITLE
missing `node_indices` method

### ISSUE THREAD

**Issue by kieranlblack** [Qiskit/rustworkx#1036]
### Information

- **rustworkx version**: 0.13.2
- **Python version**: 3.12.0
- **Rust version**: rustc 1.73.0 (cc66ad468 2023-10-03)
- **Operating system**: Microsoft Windows 11 Pro 10.0.22631 Build 22631

### What is the current behavior?
`node_indices` doesn't seem to be defined in the PyO3 `pyi` files.

### What is the expected behavior?
According to the documentation, this method should exist: 
https://qiskit.org/ecosystem/rustworkx/apiref/rustworkx.PyDiGraph.node_indices.html#rustworkx.PyDiGraph.node_indices

### Steps to reproduce the problem
Look at [`graph.pyi`](https://github.com/Qiskit/rustworkx/blob/main/rustworkx/graph.pyi) for example. Files probably just need to be regenerated.

**Comment by IvanIsCoding** [comment]
#967 includes `node_indices` so it should be fixed once it is merged and released in 0.14
