### ISSUE TITLE
Feature: find bridges

### ISSUE THREAD

**Issue by robinvd** [Qiskit/rustworkx#1039]
### What is the expected enhancement?

I currently use networkx for a project, the only missing functionality preventing me from trying out this lib is a method for finding the bridges in a graph!

method in networkx: https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.bridges.bridges.html#networkx.algorithms.bridges.bridges

i found an implementation in this rust lib, but i dont know if youre open to using extra libs: https://docs.rs/graphalgs/latest/graphalgs/connect/fn.find_bridges.html

**Comment by IvanIsCoding** [comment]
We already have `rustworkx.articulation_points` and `rustworkx.biconnected_components` so we already have the algorithms implemented. We just need to tweak it to return bridges instead of components

**Comment by inmzhang** [comment]
I would like to look into this when I have time
