### ISSUE TITLE
Add function to compute the maximum bisimulation of a graph

### ISSUE THREAD

**Issue by sander-hergarten** [Qiskit/rustworkx#1075]
### What is the expected enhancement?
Compute the maximum bisimulation natively in rust. A native rust implementation of algorithms such as Paige-Tarjan would be significantly faster than anything in python. 

There are decent native python implementation i have found but unfortunately they don't scale well to large graphs:
https://github.com/fandreuz/BisPy

**Comment by sander-hergarten** [comment]
Since i need this functionality for a project i am working on i would implement this anyways. This is more to see if this is something i can make a pull request for afterwords.

**Comment by IvanIsCoding** [comment]
Pull requests are welcome! I think if you submit  Paige-Tarjan to `rustworkx` it will get merged.

You already have the algorithm you want to implement in mind. [Check the contributing guide](https://github.com/Qiskit/rustworkx/blob/main/CONTRIBUTING.md) and once you have a draft feel free to start the request

**Comment by IvanIsCoding** [comment]
Closed by #1089
