### ISSUE TITLE
Support for "long" attribute type in GraphML

### ISSUE THREAD

**Issue by jamesdbaker** [Qiskit/rustworkx#1140]
The GraphML spec (http://graphml.graphdrawing.org/xmlns/1.0rc/graphml-attributes.xsd) states that the allowed attribute types are:

- boolean
- int
- long
- float
- double
- string

However, loading a GraphML file with an attribute type of long (e.g. `<key id="d0" for="edge" attr.name="weight" attr.type="long"/>` fails with: 

```
Exception: Invalid 'attr.type' attribute in key with id=d0.
```

The issue seems to be that the Type enum doesn't have a Long type. Could this be added?

https://github.com/Qiskit/rustworkx/blob/af0d36caa3d3b3488bdb0297b2014e5f3154f994/src/graphml.rs#L118-L124

**Comment by IvanIsCoding** [comment]
Indeed we will probably map them to isize https://github.com/Qiskit/rustworkx/blob/af0d36caa3d3b3488bdb0297b2014e5f3154f994/src/graphml.rs#L129 likes we already do with `int`
