### ISSUE TITLE
Move `collect_bicolor_runs()` functionality to rustworkx-core

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/rustworkx#1166]
The `collect_bicolor_runs()` function is only exposed via a Python interface currently:

https://github.com/Qiskit/rustworkx/blob/ab93329be6d8aaccb6c090f4b3ab6f9540ee8114/src/dag_algo/mod.rs#L627-L754

We should port it to rustworkx-core, so that rust users can leverage the function.

One tweak that probably makes sense for the rustworkx-core version is that instead of returning a `Vec` of `Vec`s of node weights we should have it return of an iterator of `Vec`s node ids. This would be more flexible and performant for rust space users and for the python side of rustworkx we can just collect the iterator to a `Vec` (for backwards compatibility).

**Comment by ElePT** [comment]
I'm interested!

**Comment by raynelfss** [comment]
This seems to have been completed. Could someone close the issue?
