### ISSUE TITLE
 Move dag longest path functions to rustworkx-core

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/rustworkx#1168]
The dag longest path family of functions:

- `dag_longest_path`
- `dag_longest_path_length`
- `dag_weighted_longest_path`
- `dag_weighted_longest_path_length`

Are all built using the following rust module:
 
https://github.com/Qiskit/rustworkx/blob/ab93329be6d8aaccb6c090f4b3ab6f9540ee8114/src/dag_algo/longest_path.rs

and are only exposed via the Python interface currently. We should move these to rustworkx-core so that Rust users can take advantage of them. Realistically probably adding the `longest_path` module is sufficient as the `pyfunctions` currently exposed are just an interface layer for Python and don't any extra value for rust consumers.

**Comment by henryzou50** [comment]
I am interested in this issue. Can you assign this to me?

**Comment by mtreinish** [comment]
Fixed by #1192
