### ISSUE TITLE
Update PyO3 to 0.22.x

### ISSUE THREAD

**Issue by IvanIsCoding** [Qiskit/rustworkx#1250]
### What is the expected enhancement?

This is mostly a reminder that we need to update to 0.22.1 (or later) following https://pyo3.rs/v0.22.0/migration.html

**Comment by mtreinish** [comment]
We're going to be blocked on rust-numpy for this. There a couple of open PRs there working on pyo3 0.22.x compatibility. Once that's released then we can start this.
