### ISSUE TITLE
PyDiGraph Type Hinting not working, TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by drauh** [Qiskit/rustworkx#1271]
### Information

- **rustworkx version**: 0.15.1
- **Python version**: 3.9, 3.11 and 3.10 (Colab)
- **Rust version**: None
- **Operating system**: Ubuntu 22.04 and Google Colab

### What is the current behavior?

```python
import rustworkx as rx

graph: rx.PyDiGraph[str, str] = rx.PyDiGraph()
```

```
import rustworkx as rx
----> graph: rx.PyDiGraph[str, str] = rx.PyDiGraph()

TypeError: 'type' object is not subscriptable
```

### What is the expected behavior?

It seems that other users manage to use type hinting as shown in https://github.com/Qiskit/rustworkx/issues/1242. I can't understand why it doesn't work on both systems I tested, and I can't find anything in the documentation about it.

### Steps to reproduce the problem

Go to Google Colab and run:
```python
!pip install rustworkx[all]
import sys
print(sys.version)
!ldd --version
import rustworkx as rx

graph: rx.PyDiGraph[str, str] = rx.PyDiGraph()
```

**Comment by drauh** [comment]
Thank you very much for your answer. I apologize for not trying the `from __future__ import annotations` earlier. I can confirm that using this approach works on Python versions 3.9 through 3.12. However, without using the `__future__` import, the code still doesn't work, even on Python 3.12.4 (I just created a brand new environment for testing this).
![image](https://github.com/user-attachments/assets/f8a5c17a-0854-4bf5-b9f6-10deb5e81c0b)
That said, this solution does indeed solve the problem for me. Thank you!

**Comment by IvanIsCoding** [comment]
I guess PEP 563 is not yet mandatory in any version so you are correct. All versions need the `__future__`
