### ISSUE TITLE
Add `is_semiconnected` function.

### ISSUE THREAD

**Issue by georgios-ts** [Qiskit/rustworkx#446]
### What is the expected enhancement?
A graph is semiconnected if, and only if, for any pair of nodes, either one is reachable from the other, or they are mutually reachable. 

For reference, see https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.is_semiconnected.html#networkx.algorithms.components.is_semiconnected

For the implementation, we can consider adapting `petgraph::condesation` function https://docs.rs/petgraph/0.6.0/petgraph/algo/fn.condensation.html. We can't use it directly since it only works with `petgraph::Graph` but we have a `petgraph::StableGraph` as our underlying graph data structure.

**Comment by SECRETSTAR01** [comment]
Hey @georgios-ts !

Can you please tell where do we need to add this function, where are we going to use it ?

**Comment by Procatv** [comment]
Hi, I was wondering if I could be assigned to this issue!

**Comment by mtreinish** [comment]
Of course, I've assigned the issue to you.
