### ISSUE TITLE
Implement simple_cycles() Johnson Algorithm

### ISSUE THREAD

**Issue by chikko80** [Qiskit/rustworkx#622]
### What is the expected enhancement?
Networkx has an algorithm for finding all cycles in a directed graph:

[simple_cycles](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.cycles.simple_cycles.html)

it's based on the Research of [D. B. Johnson in 1975 ](https://doi.org/10.1137/0204007)

Would love to see a rust implementation of that!

**Comment by chikko80** [comment]
@mtreinish 
I appreciate the fast implementation!
I tested your code on my current graph in comparison to networkx.
Just want to let you know that there is probably a little bug in the code.
On my current graph networkx returns about 7000 cycles and the retworkx implementation returns only 1.
Maybe just a wrong condition

**Comment by chikko80** [comment]
Hi @mtreinish,
I just wanna kindly ask how your current workload is and when we could expect the algorithm to be finished.
I know, you are doing that in your free time so absolutely no pressure.
I am just curious and looking forward to the implementation because it would fit into my current university project perfectly.

**Comment by mtreinish** [comment]
I think I've got it working now, see https://github.com/Qiskit/retworkx/pull/633 let me know if you still have issues with it. I still need to do more testing and add more tests to the PR

**Comment by chikko80** [comment]
Working as expected!
