### ISSUE TITLE
crates.io still has retworkx-core, not rustworkx-core

### ISSUE THREAD

**Issue by lochsh** [Qiskit/rustworkx#662]
### Information

- **retworkx version**: N/A
- **Python version**: 3.8.11
- **Rust version**: 1.63.0
- **Operating system**: Ubuntu 20.04

### What is the current behavior?

```
$ cargo add rustworkx-core
    Updating crates.io index
error: the crate `rustworkx-core` could not be found in registry index.

```

### What is the expected behavior?
That rustworkx-core be on crates.io so that the documentation in https://github.com/Qiskit/rustworkx/blob/main/rustworkx-core/README.md#usage is correct.

### Steps to reproduce the problem
See above current behaviour.

---

Thanks! In the meantime I wil use retworkx-core.

**Comment by mtreinish** [comment]
Thanks for filing a report on this, we're preparing the 0.12.0 release which will publish the rustworkx-core crate to crates.io. There are just some last few issues we're trying to resolve before tagging the release, you can see the burn down list here: https://github.com/Qiskit/rustworkx/milestone/8

**Comment by lochsh** [comment]
Ah great, thank you!

**Comment by IvanIsCoding** [comment]
Done: https://crates.io/crates/rustworkx-core
