### ISSUE TITLE
Docs link broken, and rustworkx pypi project not reachable

### ISSUE THREAD

**Issue by LBergeronPhotonic** [Qiskit/rustworkx#664]
### Information

- **retworkx version**: 11.0
- **Python version**: 3.9
- **Rust version**: rustc 1.63.0
- **Operating system**: Windows

### What is the current behavior?
1. This link: https://qiskit.org/documentation/rustworkx 
directing to a Not Found page.

2. Additionality, the pypi link for rustworkx is also broken: https://pypi.org/project/rustworkx/

Are the pypi and docs server down?

### What is the expected behavior?
The link should direct to the docs or pypi projects.

### Steps to reproduce the problem
Click the links: 
https://qiskit.org/documentation/rustworkx 
https://pypi.org/project/rustworkx/

**Comment by IvanIsCoding** [comment]
For the docs: we are working on it at #665

For the pypi release: it is not broken, `rustworkx` as of now is not yet released under the new name (see #662). In the meantime, use `retworkx`
