### ISSUE TITLE
rustworkx not available via PyPi (pip)

### ISSUE THREAD

**Issue by dsvandet** [Qiskit/rustworkx#673]
### Information

- **retworkx version**:
- **Python version**:
- **Rust version**:
- **Operating system**:

This was observed by Varun Seshadri @isolatedinformation

### What is the current behavior?

`rustworkx` not available via PyPi (pip)

### What is the expected behavior?

Should be available via pip according to documentation.

### Steps to reproduce the problem

`pip install rustworkx`

or search PyPi site

**Comment by IvanIsCoding** [comment]
It is available under the old name of `retworkx`, you can install:

```
pip install retworkx
```

The package under the new name will be available soon. If you really need one of the features of the new release, [follow the instructions on how to install from source](https://github.com/Qiskit/rustworkx#building-from-source)

**Comment by IvanIsCoding** [comment]
It is now available at https://pypi.org/project/rustworkx
