### ISSUE TITLE
Visualization failure with latest matplotlib 3.6.0

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/rustworkx#680]
### Information

- **retworkx version**: 0.11.0
- **Python version**: 3.8
- **Rust version**:
- **Operating system**: Ubuntu 20.04.5 or MacOS 12.6

### What is the current behavior?
With the recent matplotlib 3.6, the following fails:
```
from retworkx import PyGraph
from retworkx.visualization import mpl_draw
from matplotlib import pyplot as plt

graph = PyGraph(multigraph=False)
a = graph.add_node("A")
b = graph.add_node("B")
c = graph.add_node("C")

# add_edges_from takes tuples of node indices and weights,
# and returns edge indices
graph.add_edges_from([(a, b, 1.5), (a, c, 5.0), (b, c, 2.5)])

mpl_draw(graph=graph)
plt.show()
```
```
  mpl_draw(graph=graph)
  File "/Users/manoel/opt/anaconda3/envs/Qiskitenv/lib/python3.8/site-packages/retworkx/visualization/matplotlib.py", line 212, in mpl_draw
    if cf._axstack() is None:
TypeError: '_AxesStack' object is not callable
```

### What is the expected behavior?
It should show graph

### Steps to reproduce the problem
Run the sample above

**Comment by IvanIsCoding** [comment]
Thanks for reporting this. Our `mpl_draw` function is forked from NetworkX, so we are also experiencing https://github.com/networkx/networkx/issues/5938

Fortunately, I believe after we apply https://github.com/networkx/networkx/pull/5937 it should be fixed
