### ISSUE TITLE
Migrate `steiner_tree()` and `metric_closure()` to rustworkx-core

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/rustworkx#769]
### What is the expected enhancement?

The `metric_closure()` and `steiner_tree()` functions available at: https://github.com/Qiskit/rustworkx/blob/main/src/steiner_tree.rs should be straightforward to port to rustworkx-core and rework as generic for any petgraph graph and then update the python functions to call the inner rustworkx-core function. This will then expose this functionality to any rust users that might want this functionality.

**Comment by yoshida-ryuhei** [comment]
Can I be assigned to this?

**Comment by mtreinish** [comment]
Sure thing, I've assigned the issue to you

**Comment by yoshida-ryuhei** [comment]
Thank you.
I am going to implement this patch!

**Comment by mtreinish** [comment]
This was implemented in https://github.com/Qiskit/rustworkx/pull/1103
