### ISSUE TITLE
Wrong `eigenvector_centrality` test case in `rustworkx-core`

### ISSUE THREAD

**Issue by IvanIsCoding** [Qiskit/rustworkx#798]
### Information

- **rustworkx version**: master
- **Python version**: 3.10
- **Rust version**: 1.61
- **Operating system**: Linux

### What is the current behavior?

The `assert_almost_equal!` method in rustworkx-core's test suite for `eigenvector_centrality`  is implemented incorrectly. It always returns true and never panics. This let a bad test case slip through. (see https://github.com/Qiskit/rustworkx/blob/main/rustworkx-core/src/centrality.rs#L433)

### What is the expected behavior?

Implement the correct `assert_almost_equal!` like in #797. After, fix the test case.

### Steps to reproduce the problem

Replace any values in the `expected_values` array and the test case still passes. Implement the correct `assert_almost_equal` and the test case fails.

**Comment by mustapha-saad-codeStar** [comment]
Hi, Can I work on this issue?

**Comment by IvanIsCoding** [comment]
> Hi, Can I work on this issue?

Yes I have assigned the issue to you. You might want to check https://github.com/Qiskit/rustworkx/blob/main/CONTRIBUTING.md, it has some tips for your first contribution

**Comment by mustapha-saad-codeStar** [comment]
Right, thank you. I would go through the codebase right now and create a pull request when I am done...

**Comment by mustapha-saad-codeStar** [comment]
I can't seem to find eigenvector_centrality test case

Can you please precisely  link the folder where the issue is here? @IvanIsCoding

**Comment by IvanIsCoding** [comment]
> I can't seem to find `eigenvector_centrality` test case
> 
> Can you please precisely link the folder the issue is here? @IvanIsCoding

The test is in the centrality.rs file, this link takes you to the line defining the incorrect macro used in test cases is: https://github.com/Qiskit/rustworkx/blob/main/rustworkx-core/src/centrality.rs#L433

**Comment by mustapha-saad-codeStar** [comment]
Okay, thank you.

I am going to do it this way then,

The deliverables would be:
1 - I would separate all the test functions in `centrality.rs` into its own file in the `test` folder (following the separation of concern rule),

2 - Then fix the `assert_almost_equal` test case to test the function correctly...

Let me know if i can do it this way so I can start working on it right away...

**Comment by mustapha-saad-codeStar** [comment]
Let me know if i can do it this way so I can start working on it right away...

**Comment by IvanIsCoding** [comment]
> Okay, thank you.
> 
> I am going to do it this way then,
> 
> The deliverables would be: 1 - I would separate all the test functions in `centrality.rs` into its own file in the `test` folder (following the separation of concern rule),
> 
> 2 - Then fix the `assert_almost_equal` test case to test the function correctly...

That is correct
