### ISSUE TITLE
Node and Edge Filtering and Selection

### ISSUE THREAD

**Issue by dhuang-hub** [Qiskit/rustworkx#800]
### What is the expected enhancement?

It would be great to have the ability to filter a graph's nodes and edges by some abstract criteria conditioned on a node's data payload.

A analogous feature seen in `igraph` would be the methods/functions of `select` and `find`.
```
# G is some arbitrary igraph.Graph

G.vs.select(lambda v: v["weight"] > 4)  # vertex selection
G.vs.find(name="foo")
```

**Comment by danielleodigie** [comment]
Can I be assigned to this?
