### ISSUE TITLE
Transitive reduction

### ISSUE THREAD

**Issue by LaurentBergeron** [Qiskit/rustworkx#801]
### What is the expected enhancement?

A "transitive reduction" algorithm. 

Wikipedia: https://en.wikipedia.org/wiki/Transitive_reduction

Functionality should be similar to networkx: https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.dag.transitive_reduction.html

**Comment by danielleodigie** [comment]
Can I be assigned to this?
