### ISSUE TITLE
Add support to `hexagonal_lattice_graph` for periodcity and position coordinates

### ISSUE THREAD

**Issue by javabster** [Qiskit/rustworkx#803]
### What is the expected enhancement?
networkx's [`hexagonal_lattice_graph`](https://networkx.org/documentation/stable/reference/generated/networkx.generators.lattice.hexagonal_lattice_graph.html) function provides support for periodicity and setting position coordinates, and it would be great if rustworkx's `hexagonal_lattice_graph` did the same.

Definition of done:
- a `periodic` bool argument added to `hexagonal_lattice_graph`
- a `with_positions` bool argument added to `hexagonal_lattice_graph`

cc @mrossinek

**Comment by mrossinek** [comment]
You can assign this issue to @javabster and myself :+1:

**Comment by javabster** [comment]
An update on our investigation:

We've compared how networkx handles periodicity for it's hexagonal lattices and other lattice types. Some lattice types add an extra edge between nodes, but the hexagonal lattice method actually combines nodes together (using a `contracted_nodes` function). This node contraction method seems to be the best option in the hexagonal lattice case as it enables users to maintain the rows and columns format as input arguments, and using that method here in rustworkx will keep feature parity with networkx. However the `contracted_nodes` logic in networkx is a bit difficult to follow so our next step is to investigate if there is a simpler way to implement this functionality. Additionally, we think it would be beneficial for users to be able to specify which direction to implement the periodicity. Networkx implements periodicity in all directions only, however we think there are potential use cases where a user might want to generate a hexagonal lattice which is periodic in just the x or just the y direction, so we will be looking into this implementation further.

cc @mrossinek

**Comment by javabster** [comment]
hi @mtreinish we've been looking into how to best implement the periodic part of this and are first looking to mimic the logic used in[ networkx](https://networkx.org/documentation/stable/_modules/networkx/generators/lattice.html#hexagonal_lattice_graph) in `rustworkx-core/src/generators/hexagonal_lattice`. We see that `rustworkx` has a `contract_nodes` function (similar to the networkx `contracted_nodes`) that we were considering using, but it seems like that method is only accessible from the python layer of rustworkx, not in rustworkx core? Do you have a recommendation for how best to proceed? We were considering options like only implementing periodicity from the python layer, or somehow refactoring `contract_nodes` to be usable in `rustworkx-core`. Not sure what would be the best option and would appreciate your input 😄

**Comment by jpacold** [comment]
Commenting so that this can be assigned to me (see #1213)
