### ISSUE TITLE
arguments to `pass_env` in tox.ini are not comma separated

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/rustworkx#812]
`tox -epy` fails with

```
py: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'RETWORKX_TEST_PRESERVE_IMAGES RUSTWORKX_PKG_NAME'
  py: FAIL code 1 (0.00 seconds)
```

Requiring commas  was introduced in tox 4.0.6 :  https://github.com/tox-dev/tox/pull/2671

See also https://github.com/Qiskit/qiskit-terra/pull/9276

**Comment by IvanIsCoding** [comment]
I think merging the fix should be fine and done soon, but for the time being use Tox 3 instead of Tox 4 (just like our CI: https://github.com/Qiskit/rustworkx/blob/main/.github/workflows/main.yml#L87)

**Comment by IvanIsCoding** [comment]
> This is misleading:
> 
> https://github.com/Qiskit/rustworkx/blob/a5178e28a3921fd6372c523f7997187b27180b04/CONTRIBUTING.md?plain=1#L112-L114
> 
> If we are putting off switching to Tox 4 for a while, then the installation instruction should be changed.

It was true until https://github.com/Qiskit/rustworkx/pull/761 which is not too long ago
