### ISSUE TITLE
Way to iterate through nodes in a grid graph

### ISSUE THREAD

**Issue by jbecker7** [Qiskit/rustworkx#827]
Hi, 

In NetworkX, I can do the following with grid graphs:

```
#side length of triangular region
n = 6

# number of districts
k = 3 # This code only works for k = 3
# size of districts
k0 = 7 # size of district 0
k1 = 7 # size of district 1
k2 = 7

# Check District Sizes add correctly
print("Sum of district sizes == number of vertices? ", (k0 + k1 + k2) == n * (n+1) /2 )

# make grid graphs
g = nx.grid_graph([n,n])
# make into a triangular region of the triangular lattice
removelist = []
for v in g.nodes():
    if v[0] + v[1] >= n: # remove this node
        removelist.append(v)
    else: 
        if v[0]>=1: # add a diagonal edge
            g.add_edge(v, (v[0]-1, v[1]+1))
g.remove_nodes_from(removelist)

```

This hinges on being able to iterate through the nodes, but I cannot do that with RustworkX from what I can tell since they are all just None. Is there an alternative way this sort of thing should be done?

**Comment by mtreinish** [comment]
I think in your case you want to replace `graph.nodes()` with `graph.node_indices()` to get the unique identifiers for the nodes. That being said in your example it looks like networkx's grid graph generator is setting the nodes as a tuple of their coordinates in the grid, rustworkx's generator doesn't do that which I think will be the biggest issue. There is a similar issue about the lack of coordinates in the output for the hexagonal lattice graphs:  https://github.com/Qiskit/rustworkx/issues/803 Maybe  @javabster and @mrossinek can add the same functionality to the grid graph after they update the hexagonal lattice.

Just as an aside we do have a tutorial explaining some differences in using rustworkx coming from network here: https://qiskit.org/documentation/rustworkx/networkx.html which might be useful.

**Comment by mrossinek** [comment]
Thanks for the ping. We are currently focusing on getting periodicity sorted first. But even that is not on our high priority list so it might be a while before I can refer back to this. If somebody needs this earlier/any time soon they better look into this themselves rather than wait on us implementing it :slightly_smiling_face:

**Comment by jbecker7** [comment]
@mrossinek Thanks for your hard work, looking forward to those changes :)

@mtreinish Thank you so much for your reply. That makes sense that I should look at the indices instead of the nodes. I feel like my issue will come down to not being able to do the tuples, as you point out. Out of curiosity, is there a native way in RustworkX to do what I am trying to do? I have copied the code below, but I was essentially using NetworkX to look at all the different ways to break up a triangular political district for a project for a college class. :) No worries if nothing comes to mind, I appreciate the help and will close the isuse.

```
#side length of triangular region
n = 6

# number of districts
k = 3 # This code only works for k = 3
# size of districts
k0 = 7 # size of district 0
k1 = 7 # size of district 1
k2 = 7

# Check District Sizes add correctly
print("Sum of district sizes == number of vertices? ", (k0 + k1 + k2) == n * (n+1) /2 )

# make grid graphs
g = nx.grid_graph([n,n])
# make into a triangular region of the triangular lattice
removelist = []
for v in g.nodes():
    if v[0] + v[1] >= n: # remove this node
        removelist.append(v)
    else: 
        if v[0]>=1: # add a diagonal edge
            g.add_edge(v, (v[0]-1, v[1]+1))
g.remove_nodes_from(removelist)

# Draw the grid graph we're working with
plt.figure() # start a figure
nx.draw(g, pos = {x:(x[0]+x[1], x[1] + (n-x[0])) for x in g.nodes()})
plt.show()

plans = [] #initially have no valid plans, is an empty list

# Make District 0
# Must contain (0,0)
# Must be conencted
# Must be of size k0
dist0 = [d for d in (list(it.combinations(g.nodes(), k0)))
            if ((0,0) in d) and (nx.is_connected(g.subgraph(d)))]

print("Number of possible district 0's:", len(dist0))

#Loop through all possible district 0's
for d0 in dist0:
    # find vertex that has to be in district 1
    found1 = False
    dist1vtx = (0,0)
    for i in range(n):
        for j in range(n-i):
            #if (j,i) is the first vertex outside of district 0 that we've found
            if (j,i) not in d0 and found1 == False:
                dist1vtx = (j,i) #this vertex must be in district 1
                found1 = True
                
    # make list of vertices not in district 0
    notindistrict0 = [v for v in g.nodes() if v not in d0]
    #print(d0)
    #print(notindistrict0)
    
    district1conn = [d1 for d1 in list(it.combinations(notindistrict0, k1))
                         if (dist1vtx in d1) and 
                         (nx.is_connected(g.subgraph(d1)))]
        
    for d1 in district1conn:
            # d2 is whatever's not in d0 or d1
            d2 = [v for v in notindistrict0 if v not in d1]
            
            if nx.is_connected(g.subgraph(d2)):
                # add plan to list of plans
                plan = dict()
                for v in d0:
                    plan[v] = 0
                for v in d1:
                    plan[v] = 1
                for v in d2:
                    plan[v] = 2
                plans.append(plan)
```
