### ISSUE TITLE
PyGraph not typed correctly in VSCode, disallowing autocomplete

### ISSUE THREAD

**Issue by thomasaarholt** [Qiskit/rustworkx#832]
### Information

- **rustworkx version**: 0.12.1
- **Python version**: 3.10.9
- **Rust version**: Not installed, installed via [wheel](https://pypi.org/project/rustworkx/#files)

- **Operating system**:
Debian Buster

### What is the current behavior?
VSCode is unable to parse the type of PyGraph, see below.

<img width="404" alt="Screenshot 2023-03-14 at 07 49 48" src="https://user-images.githubusercontent.com/2721423/224918597-ebc8eb66-aa3c-4c32-a13f-aa1c7bdfe81c.png">

<img width="298" alt="image" src="https://user-images.githubusercontent.com/2721423/224918117-28268df4-cba4-4e5e-b0ef-34268f85d33e.png">

This makes it very difficult to write code, especially while getting used to a new API.

Autocompletion works in iPython, and assumedly, the Jupyter Notebook (both use Jedi).

### What is the expected behavior?
VSCode should identify the type of the graph

### Steps to reproduce the problem
In VSCode: 
```python
import rustworkx

graph = rustworkx.PyGraph()

a = graph.add_node("A")
```

**Comment by IvanIsCoding** [comment]
We just merged #401 which should fix that. It has not been released yet.

Would you mind installing from the main branch and sharing what you see?

**Comment by thomasaarholt** [comment]
Wahey! It works great!

The typing here is very cool. Took me a moment to figure out, but its quite useful.
<img width="928" alt="image" src="https://user-images.githubusercontent.com/2721423/225579878-9a5b40f9-41cb-4141-ae4c-9667fcc265b9.png">

Two suggestions:
- Rename the TypeVars `S` and `T` to `NodeType` and `PayloadType`
- Rename the `edge` argument to `payload`.

**Comment by thomasaarholt** [comment]
Hilariously, the above code doesn't actually run 😅 
```python
g: rx.PyGraph[tuple[int, int], float] = rx.PyGraph() # this typing is very cool

n1 = g.add_node((1,2))
n2 = g.add_node((3,4))

g.add_edge(n1, n2, 10)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[52], line 1
----> 1 g: rx.PyGraph[tuple[int, int], float] = rx.PyGraph() # this typing is very cool
      3 n1 = g.add_node((1,2))
      4 n2 = g.add_node((3,4))

TypeError: type 'rustworkx.PyGraph' is not subscriptable
```

Is this technically a bug? Without it, the node and payload types are Unknown:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/2721423/225619259-fec3978b-8541-42d8-bfbe-3e4666f41e57.png">

<img width="772" alt="image" src="https://user-images.githubusercontent.com/2721423/225619159-299aebd2-649a-4c68-833b-b56bb321ec55.png">

**Comment by thomasaarholt** [comment]
See my comment above - I can't index into PyGraph (not subscriptable).

**Comment by IvanIsCoding** [comment]
> See my previous comment - I can't index into PyGraph (not subscriptable). That's the error i get when I'm adding the type hint.

This is related to [PEP 563](https://peps.python.org/pep-0563/), the following code works:

```python
from __future__ import annotations

import rustworkx as rx

g: rx.PyGraph[tuple[int, int], float] = rx.PyGraph() # this typing is very cool

n1 = g.add_node((1,2))
n2 = g.add_node((3,4))

g.add_edge(n1, n2, 10)
```

**Comment by thomasaarholt** [comment]
Came back to this this week, and I now understand the error better! PyGraph is now correctly typed via being imported in rustworkx.pyi. Thank you for the helpful comments - the import from `__future__` was very interesting to read about!

I've installed the master branch, but now I don't understand why, e.g. `distance_matrix` is not being imported into the namespace. It was my understanding that since it is defined in `__init__.py`, it should be found by the type checker. I even tried adding it to `__all__ = ["distance_matrix"]` (and reinstalling), without luck. I considered making a new issue, but this is strongly related to the original issue, so commented here.

<img width="714" alt="Screenshot 2023-05-17 at 13 28 23" src="https://github.com/Qiskit/rustworkx/assets/2721423/6416d77e-cc00-4288-94d2-715be690ada4">
