### ISSUE TITLE
Investigate tox alternatives

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/rustworkx#852]
### What is the expected enhancement?

As a follow up to #851 and the tox 4 release series more generally along with the instability and backwards compatibly issues associated with that release. We should investigate looking at an alternative tool for managing our CI and local development environments and running of tests and other checks. The top contender in my mind is https://github.com/wntrblm/nox which I know pyo3 has moved to and it seems to work well for them. Personally I've not tried it so this issue is more track an investigation into alternative tooling and figure out what our migration plan away from tox would look like.

**Comment by IvanIsCoding** [comment]
I will take a look into nox.

Switching into it just because of the Tox 4.0 update seems an overkill. Nevertheless, the Python syntax is a great plus. We are a Python library so glueing something in Nox seems to be easier than in Tox
