### ISSUE TITLE
a new algorithm that returns all possible shortest paths for a source target pair

### ISSUE THREAD

**Issue by rok24** [Qiskit/rustworkx#933]
At the moment digraph_dijkstra_shortest_paths returns only one shortest path for a source-target pair. It would be nice to see all the possible shortest paths with the same length for a source-target pair. 
Currently networkx has this functionality in all_shortest_paths function and it returns all possible shortest paths.

**Comment by prpr2770** [comment]
@mtreinish I'd like to work on this problem. Please let me know how I may proceed, as I'm new to this project.

**Comment by mtreinish** [comment]
Sure thing, I've assigned you the issue. The contributing guide: https://github.com/Qiskit/rustworkx/blob/main/CONTRIBUTING.md has some general guidelines for writing PRs. Besides that in this case you'll want to add 2 new functions to https://github.com/Qiskit/rustworkx/blob/main/src/shortest_path/mod.rs that computes all the shortest paths between two nodes for both graphs and digraphs

**Comment by prpr2770** [comment]
@mtreinish Thank you for assigning this and sharing the resources. I shall send you an update as soon as its completed.

**Comment by lucasvanmol** [comment]
Hi @mtreinish, since this hasn't seen much activity recently, could I take this over? I have something that works, but would like some input on the best way to implement it.

**Comment by mtreinish** [comment]
@lucasvanmol sure, this has been idle for > 2 months so I've reassigned the issue to you. I'll try to take a look at your WIP PR soon.

**Comment by IvanIsCoding** [comment]
Closed by #1017
