### ISSUE TITLE
rustworkx.directed_gnp_random_graph doesn't produce random graphs

### ISSUE THREAD

**Issue by yurivict** [Qiskit/rustworkx#950]
### Information

- **rustworkx version**: 0.13.0
- **Python version**: 3.9
- **Rust version**: 1.71.0
- **Operating system**: FreeBSD 13.2

### What is the current behavior?
rx.directed_gnp_random_graph(20, 0.5) consistently produces nodes with only one edge, when with ```2*(19)=38``` possible edges the chance of this is extremely low: ```0.5^38 * 38 = 1.38 * 10^-10```.

### What is the expected behavior?
19 edges on average should be present for each node.

### Steps to reproduce the problem
Run this script:
```
import rustworkx as rx

import os
import tempfile

import pydot
from PIL import Image

G = rx.directed_gnp_random_graph(20, 0.5)

dot_str = G.to_dot(
    lambda node: dict(
        color='black', fillcolor='lightblue', style='filled'))
dot = pydot.graph_from_dot_data(dot_str)[0]

dot.write_png("G.png")
```

![image](https://github.com/Qiskit/rustworkx/assets/271906/05c66931-186c-403c-a442-14bf9673cb31)

![image](https://github.com/Qiskit/rustworkx/assets/271906/0b87d81a-9986-4b7f-905a-a92869670311)

![image](https://github.com/Qiskit/rustworkx/assets/271906/725c7486-b9ba-497b-aae6-d42c5758f2c3)

**Comment by enavarro51** [comment]
Yeah, it appears that the ones with a lower node number have fewer edges. I'll take a look at the algorithm.
