### ISSUE TITLE
rustworkx.all_simple_paths returns empty list when the min_depth argument is 0

### ISSUE THREAD

**Issue by yurivict** [Qiskit/rustworkx#955]
### Information

- **rustworkx version**: 0.13.0
- **Python version**: 3.9
- **Rust version**: 1.71.0
- **Operating system**: FreeBSD 13.2

### What is the current behavior?
empty list is returned

### What is the expected behavior?
correct list is returned

### Steps to reproduce the problem
```len(rx.all_simple_paths(G, 1, 2, 0, 25))``` for any graph

The description says: ```min_depth (int) – The minimum depth of the path to include in the output list of paths. By default all paths are included regardless of depth, setting to 0 will behave like the default.```

The default is None, but the 0 value doesn't behave as the default value.

**Comment by abhamra** [comment]
Hi, I'd like to tackle this problem. This is my first time doing open source contributions, and all I've done so far is fork the repo, clone the forked repo, and then create a dev branch on the forked repo. Any other guidance would be appreciated!

**Comment by IvanIsCoding** [comment]
You need to update the code in the [connectivity](https://github.com/Qiskit/rustworkx/blob/23c96626e8190e4dacb3a4d8ec713977cf0abe28/src/connectivity/mod.rs#L530) module for `graph_all_simple_paths` and `digraph_all_simple_paths`
