### ISSUE TITLE
mypy cannot find type-specific functions

### ISSUE THREAD

**Issue by Xemorr** [Qiskit/rustworkx#960]
### Information

- **rustworkx version**: 0.13.1
- **Python version**: 3.9
- **Rust version**: N/A, not installed
- **Operating system**: Ubuntu 20.04

### What is the current behavior?
PyCharm will think a method exists, I'll go to use it and then run mypy against it, mypy then says "Module has no attribute "graph_dijkstra_shortest_paths"  [attr-defined]"

### What is the expected behavior?
Mypy would understand the error

### Steps to reproduce the problem
I have not been able to get to the bottom of why this is happening, the mypy version is 3.9 **not** 3.7, so is not a duplicate of that issue. 

I just pip installed rustworkx, added 0.13.1 to my requirements file and then tried to use it in our codebase.

**Comment by IvanIsCoding** [comment]
Can you provide the commands options passed to mypy and make a minimal reproducible example?

Currently our library is only partially typed. This means that only some type stubs are available, while the others they use the function signature from Rust which is not very informative. Some flags in mypy May affect how it interacts with partially typed packages

**Comment by Xemorr** [comment]
```
python_version = 3.9
warn_unused_configs = True
no_implicit_optional = True
warn_redundant_casts = True
mypy_path = stubs/
disallow_untyped_defs = True
disallow_untyped_calls = True
warn_return_any = True
warn_unreachable = True
ignore_missing_imports = False
scripts_are_modules = True
plugins = pydantic.mypy
show_error_codes = True
```

**Comment by Xemorr** [comment]
See this repository for a broken example: https://github.com/Xemorr/RustworkXBrokenStubs

**Comment by Xemorr** [comment]
I still get `main.py:9: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]`
with implicit_reexport = False in my small repository

**Comment by Xemorr** [comment]
I've added types, pycharm understands what's going on, mypy still has no idea.

**Comment by IvanIsCoding** [comment]
Indeed, `mypy` is ignoring our `py.typed` file completely and does not show any functions - even the one in the modules. #963 should help fix this, let's see

**Comment by Xemorr** [comment]
Great, thanks for your work!
