### ISSUE TITLE
Blender add-on or console: import rustworkx results in error No module named 'rustworkx.rustworkx'

### ISSUE THREAD

**Issue by dballesg** [Qiskit/rustworkx#980]
### Information

- **rustworkx version**: 0.13.1
- **Python version**: Blender internal Python  3.10.12
- **Rust version**: Not installed
- **Operating system**: Windows

### What is the current behavior?

I am developing a Blender add-on and I wanted to use use rustworkx to do some graphs. 

My problem is every time my add-on try to import it I got the error: No module named 'rustworkx.rustworkx'
I debugged my add-on and the problem comes from this line in rustworks __init__.py
[https://github.com/Qiskit/rustworkx/blob/main/rustworkx/__init__.py#L13](url)

Blender has it's own user site-packages directory and I'm sure rustworkx installs properly on it. 
I created a Blender Operator to install it on Blenders User Site-Packages dir. 
See the attached screenshot.

I've tried any thing I could think off, last one is trying to lazy import rustworks and it's not working either.

This is an output from the Blender's console:

>Lazy Importing Dependency :
>       Module  : rustworkx
>      Alias   : rx
rustworkx Spec    : ModuleSpec(name='rustworkx', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000279629BBD40>, origin='G:\\blender-git\\build_windows_x64_vc16_Debug\\bin\\Debug\\4.0\\python\\lib\\site-packages\\rustworkx\\__init__.py', submodule_search_locations=['G:\\blender-git\\build_windows_x64_vc16_Debug\\bin\\Debug\\4.0\\python\\lib\\site-packages\\rustworkx'])
rustworkx Loader  : <importlib.util.LazyLoader object at 0x00000279629BB200>
Traceback (most recent call last):
  File "G:\blender-git\build_windows_x64_vc16_Debug\bin\Debug\4.0\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\David\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\locality\__init__.py", line 15, in <module>
    from .sampling import shape
  File "C:\Users\David\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\locality\sampling\shape.py", line 17, in <module>
    rx = import_dependencies.lazy_import(module='rustworkx',alias='rx')
  File "C:\Users\David\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\locality\import_dependencies.py", line 43, in lazy_import
    print(F"{' ':<{len('Imported Module')-len(module)}} Imported Module  : {imported_module}")
  File "G:\blender-git\build_windows_x64_vc16_Debug\bin\Debug\4.0\python\lib\importlib\util.py", line 247, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "G:\blender-git\build_windows_x64_vc16_Debug\bin\Debug\4.0\python\lib\site-packages\rustworkx\__init__.py", line 13, in <module>
    from .rustworkx import *
  File "G:\blender-git\build_windows_x64_vc16_Debug\bin\Debug\4.0\python\lib\site-packages\rustworkx\__init__.py", line 13, in <module>
    from .rustworkx import *
ModuleNotFoundError: No module named 'rustworkx.rustworkx'

You can see there is getting installed and loaded from the right location:
`
origin='G:\\blender-git\\build_windows_x64_vc16_Debug\\bin\\Debug\\4.0\\python\\lib\\site-packages\\rustworkx\\__init__.py', submodule_search_locations=['G:\\blender-git\\build_windows_x64_vc16_Debug\\bin\\Debug\\4.0\\python\\lib\\site-packages\\rustworkx']
`

I tried to modify the line 'from .rustworkx import *' to 'from . import *' that should be the right way, there is not an existing rustworkx directory inside the main rustworkx directory.

But then it fails on the line [https://github.com/Qiskit/rustworkx/blob/main/rustworkx/__init__.py#L18](url) with:
`File "G:\blender-git\build_windows_x64_vc16_Debug\bin\Debug\4.0\python\lib\site-packages\rustworkx\__init__.py", line 18, in <module>
    sys.modules["rustworkx.generators"] = generators
NameError: name 'generators' is not defined`

### What is the expected behavior?
Importing rustworkx should work as any other Python package.

### Steps to reproduce the problem

Difficult unless I share the source code of the add-on. :-(

My add-on can install as well https://github.com/networkx/networkx.
And that package is installed in Blender''s user site-packages and doesn't produce any import errors.

Thanks in advance
David Ballesteros
![explorer_2023-09-11_19-05-15](https://github.com/Qiskit/rustworkx/assets/13033276/45cb2c62-e9ff-44ef-9c55-fd17d1ecc53f)

**Comment by IvanIsCoding** [comment]
Can you share a minimum reproducible example? We are looking specifically for which folder you are running your Python script in, even if through Blender. This will help us address the issue.

The error you shared suggests that you are either running the code in the same folder as the `rustworkx` code or that the `rustworkx` is in your path. If you execute it in another directory or change your system path, it could fix the issue

**Comment by dballesg** [comment]
Hi Ivan, 

I'm still thinking how can I provide a working sample, needs to be a reduced version of my add-on or a bundled script in a blender file. And that last option worries me due to the execution paths blender uses in that case.

I'm using a compiled version of Blender, I'm going to update it to see if that helps.
My directories are this:

`Python Binary: G:\blender-git\build_windows_x64_vc16_Debug\bin\Debug\4.0\python\bin\python_d.exe`
`Blender User Site-Packages: G:\blender-git\build_windows_x64_vc16_Debug\bin\Debug\4.0\python\lib\site-packages`
`Blender add-on directory: C:\Users\MyUser\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\MyAddon`

In the Blneders developers chat suggeted to run Blendr as an admin but it didn't worked either. 
I'n going to try your suggestion of running or installing it on another directory and see how it goes.
I will let yuou know.

Thanks in advance, 
David Ballesteros

**Comment by dballesg** [comment]
Hi again, 

I've managed to do a small installation add-on that works. 
It's based on the code that originally I used to install dependencies and I'm currently using on my add-on.
Now I need to figure out what I did differently on my add-on.

That code it is not mine, it is from:
https://github.com/robertguetzkow/blender-python-examples/blob/master/add_ons/install_dependencies/install_dependencies.py

I've attached the modified add-on script to install and use rustworkx, in case it is useful for anyone else.

I must ads it ONLY works on Blender 3.6.2 the official release (see attached screenshot), but not on Blender 4.0 alpha. So I will report to the Blender Devs.

Thanks in advance,
David Ballesteros

[install_rustworkx_example.zip](https://github.com/Qiskit/rustworkx/files/12585460/install_rustworkx_example.zip)
![rustworkx_blender_3 -6 2_2023-09-12_12-33-28](https://github.com/Qiskit/rustworkx/assets/13033276/2735d220-61b9-46dc-9c6e-e0663609d65f)

**Comment by dballesg** [comment]
Hi again, 

I've managed to do a small installation add-on that works. 
It's based on the code that originally I used to install dependencies and I'm currently using on my add-on.
Now I need to figure out what I did differently on my add-on.

That code it is not mine, it is from:
https://github.com/robertguetzkow/blender-python-examples/blob/master/add_ons/install_dependencies/install_dependencies.py

I've attached the modified add-on script to install and use rustworkx, in case it is useful for anyone else.

I must ads it ONLY works on Blender 3.6.2 the official release (see attached screenshot), but not on Blender 4.0. So I will report to the Blender Devs.

Thanks in advance,
David Ballesteros

[install_rustworkx_example.zip](https://github.com/Qiskit/rustworkx/files/12585460/install_rustworkx_example.zip)
![rustworkx_blender_3 -6 2_2023-09-12_12-33-28](https://github.com/Qiskit/rustworkx/assets/13033276/2735d220-61b9-46dc-9c6e-e0663609d65f)
![rustworkx_blender_4 0_2023-09-12_12-35-37](https://github.com/Qiskit/rustworkx/assets/13033276/a4132a59-ca60-4187-95b3-cac97353eee3)

**Comment by dballesg** [comment]
Hi,

I found the problem. Is not rustworkx, it is pip. For some reason a Blender Debug version running pip from it's embeded Python version (3.10.13) instead of download and install a Debug version of rustworkx (rustworkx_d) it downloads and installs the Release version of rustworkx and that is why doesn't find the rustworkx package.

I solved it compiling a Release version of Blender and using that instead. 
I can debug Python on that one as well using VS Code.

I didn't tried to pass rustworkx_d as the name into the Blender Debug pip, I leave that for the moment.

I leave this temporally open if someone wants to add some comments about why pip is doing that.

Thanks in advance.
David Ballesteros

**Comment by IvanIsCoding** [comment]
I'm glad you found a solution for your problem!

For future reference, here is some debugging tips for people that get the same error message:
```
* Check that at least one folder in your PYTHONPATH contains a subfolder named rustworkx
* Check that inside that rustworkx folder, there is a rustworkx binary 
    e.g. rustworkx.cpython-311-x86_64-linux-gnu.so
* If you have a folder named rustworkx in your path (subfolder does not count), check it has the binary.
    If it doesn't, it will fail.
```
