### ISSUE TITLE
Add graph methods to to clear nodes or edges

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/rustworkx#984]
### What is the expected enhancement?

If you want to remove all the edges or nodes in a graph there should be a method on the graph classes to do this efficiently. We should add `PyDiGraph.clear()` and `PyDiGraph.clear_edges()`  (for `PyGraph` as well). This will mirror the same methods on the `StableGraph` type in petgraph to do an efficient removal of all nodes and/or edges https://docs.rs/petgraph/latest/petgraph/stable_graph/struct.StableGraph.html#method.clear and https://docs.rs/petgraph/latest/petgraph/stable_graph/struct.StableGraph.html#method.clear_edges

**Comment by abhamra** [comment]
Hi @mtreinish, I'm a newcomer to open source contributions and I'd like to have a crack at this issue. Is there anything I should look at or do before I get started? Eager to help!
