### ISSUE TITLE
Release Python 3.12 wheels

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/rustworkx#986]
### What is the expected enhancement?

This isn't especially urgent (the final release isn't even out yet), I'm mostly just making this issue so I've got something to point at in Qiskit's tracking of our own blockers against Python 3.12.

(Stable C API wheels would also be fine: #891.)

**Comment by IvanIsCoding** [comment]
I think the safest option might be releasing a 0.13.1 wheel for 3.12 because 0.14 with the ABI might take a little bit. We only have a week or so before 3.12

**Comment by cclauss** [comment]
Not anymore.

**Comment by IvanIsCoding** [comment]
Closing because the vast majority of the wheels are in https://pypi.org/project/rustworkx/0.13.2/#files

For s390x and ppc64 users, keep an eye on https://github.com/Qiskit/rustworkx/actions/runs/6398491808

**Comment by mtreinish** [comment]
Closing this now as rustworkx 0.13.2 has been released with 3.12 wheels (although we missed the trove classifier in the package metadata): https://pypi.org/project/rustworkx/0.13.2/#files
